export const CANVAS_WIDTH = 1000;
export const CANVAS_HEIGHT = 1000;

export const STAR_PATTERN_SIZE = 400;
export const STAR_PATTERN_STARS = 50;

export const SHIP_ACCELERATION = 400;
export const SHIP_DECELERATION = 50;
export const SHIP_ROTATION_SPEED = 3;
export const SHIP_MAX_SPEED = 500;
export const AI_SHIP_MAX_SPEED = 250;
export const SHIP_SHOT_INTERVAL = 0.1;
export const SHIP_SUPERSHOT_INTERVAL = 0.5;
export const SHIP_HEALING_INTERVAL = 1;
export const SHIP_HEALING_AMOUNT = 0.1;
export const SHIP_HEALING_REQUIRED_RESOURCES = 10;
export const SHIP_HEALING_DAMAGE_TIMEOUT = 5;
export const PLAYER_SHIP_DAMAGE_FACTOR = 0.5;

export const AI_MOVE_TARGET_RADIUS = 50;
export const AI_ATTACK_TARGET_RADIUS = 200;

export const PLANET_COLOR_CHANGE_FACTOR = 20;
export const PLANET_STRIPE_MIN_SIZE = 10;
export const PLANET_STRIPE_MAX_SIZE = 20;

export const BODY_UNZOOM_THRESHOLD = 700;
export const BODY_ZOOM_THRESHOLD = 500;

export const ITEM_PICKUP_RADIUS = 10;
export const ITEM_MAGNETIZED_RADIUS = 80;
export const ITEM_MAGNETIZED_SPEED = 200;
export const ITEM_HEALTH_BONUS = 0.05;

export const UNIVERSE_GENERATE_SYSTEM_MIN_MARGIN = 4000;
export const UNIVERSE_GENERATE_SYSTEM_MAX_PLANETS = 4;
export const UNIVERSE_GENERATE_SYSTEM_MIN_PLANETS = 2;
export const UNIVERSE_GENERATE_PLANET_MIN_RADIUS = 100;
export const UNIVERSE_GENERATE_PLANET_MAX_RADIUS = 200;
export const UNIVERSE_GENERATE_ORBIT_MIN_MARGIN = 500;
export const UNIVERSE_GENERATE_ORBIT_MAX_MARGIN = 700;
export const UNIVERSE_GENERATE_STAR_MIN_RADIUS = 100;
export const UNIVERSE_GENERATE_STAR_MAX_RADIUS = 200;

export const PLANET_EVOLUTION_INTERVAL = 20;
export const PLANET_EVOLUTION_REQUIRED_RESOURCES = 10;
export const PLANET_MIN_INITIAL_RESOURCES = 50;
export const PLANET_MAX_INITIAL_RESOURCES = 150;
export const PLANET_RESOURCES_PER_SECOND = 0.2;
export const PLANET_MAX_RESOURCES = 200;

export const RELATIONSHIP_ENEMY = "#f00";
export const RELATIONSHIP_ALLY = "#0f0";
export const RELATIONSHIP_UPDATE_DAMAGE_STATION = -0.05;
export const RELATIONSHIP_UPDATE_DESTROY_STATION = -0.2;
export const RELATIONSHIP_UPDATE_DAMAGE_SHIP = -0.05;
export const RELATIONSHIP_UPDATE_DESTROY_SHIP = -0.3;
export const RELATIONSHIP_UPDATE_MISSION_SUCCESS = 0.5;
export const RELATIONSHIP_UPDATE_MISSION_FAILED = -0.2;
export const RELATIONSHIP_UPDATE_MISSION_IGNORED = -0.1;

export const EVENT_STATION_DESTROYED = 0;
export const EVENT_CYCLE = 1;
export const EVENT_SHOT = 2;
export const EVENT_PICKUP_RESOURCE = 3;

export const GAME_RECAP_MIN_RELATIONSHIP_CHANGES = 10;
export const GAME_RECAP_RELATIONSHIP_CHANGES_NEUTRAL_THRESHOLD = 5;

export const MOBILE_BUTTON_SIZE = 80;

export const PROMPT_OPTION_BOX_WIDTH = 150;
export const PROMPT_OPTION_BOX_HEIGHT = 30;

export const SHIELD_RECOVERY_DELAY = 5;
export const SHIELD_RECOVERY_SPEED = 0.05;
